name: nature

channels:
- conda-forge

dependencies:

# Items required for basic level functionality
- gh-scoped-creds==4.1
- git==2.47.1
- jupyter-resource-usage=1.1.0
- jupyterhub==5.2.1
- jupyterlab==4.3.4
- jupyter_server==2.15.0
- jupyterlab-git==0.50.2
- jupytext==1.16.6
- nbgitpuller==1.2.1
- notebook==7.3.2
- python==3.11.*

# r2d installs jupyter-rsession-proxy, but in the base python env, not in the updated one
- jupyter-rsession-proxy==2.3.0

# vscode
- code-server==4.96.2
- jupyter-vscode-proxy==0.6

# spatial packages
- pystac-client==0.8.3
- odc-stac==0.3.10
- rioxarray==0.17.0
- rasterstats==0.20.0
- langchain-chroma==0.1.4
- leafmap==0.43.2
- maplibre==0.3.0
- streamlit==1.39.0

# other packages
- altair==5.4.1
- duckdb-engine==0.13.5
- earthaccess==0.10.0
- exactextract=0.2.0
- ibis-framework[pandas,duckdb]==9.3.0
- jupyterlab-myst==2.4.2
- latexmk==4.85
- mystmd==1.3.20
- planetary-computer==1.0.0
- pypdf==5.0.1
- seaborn==0.13.2
- minio=7.2.15
- dask==2025.2.0

# pip installed packages, conda is prefered
- pip==24.3.1
- pip:
  - jupyter-ai==2.31.2
  # r2d installs jupyter-shiny-proxy, but in the base python env, not in the updated one
  - jupyter-shiny-proxy==1.3
  - langchain-openai==0.3.12
  - nbconvert[webpdf]==7.16.4
