name: nature

channels:
- conda-forge

dependencies:

# Items required for basic level functionality
- gh-scoped-creds==4.1
- git==2.46.0
- jupyter-resource-usage=1.1.0
- jupyterhub==4.1.6
- jupyterlab==4.2.5
- jupyter_server==2.14.2
- jupyterlab-git==0.50.1
- jupytext==1.16.4
- nbgitpuller==1.2.1
- notebook==7.2.2
- python==3.11.*

# vscode
- code-server==4.23.1
- jupyter-vscode-proxy==0.6

# llm packages
- pystac-client==0.8.3
- odc-stac==0.3.10
- rioxarray==0.17.0
- rasterstats==0.20.0
- leafmap[mablibregl]
- streamlit==1.39.0

# other packages
- altair==5.4.1
- earthaccess==0.10.0
- ibis-framework[pandas,duckdb]==9.3.0
- jupyterlab-myst==2.4.2
- leafmap==0.36.10
- seaborn==0.13.2
 
# pip installed packages, conda is prefered
- pip==24.2
- pip:
  - jupyter-ai==2.24.0
  - langchain-ollama==0.1.3
  - langchain-openai==0.1.25
  - nbconvert[webpdf]==7.16.4
  - git+https://github.com/eodaGmbH/py-maplibregl@feature/color-utils
  - git+https://gitlab.nrp-nautilus.io/prp/jupyter-ai-nrp@9d10744ad3b9f8de9dece3fd1899f1a2d9d41a77
